//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.24 at 11:26:29 PM CEST 
//


package com.aboni.nmea.router.conf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgentBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="qos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FilterSource" type="{}FilterSource" minOccurs="0"/>
 *         &lt;element name="FilterTarget" type="{}FilterTarget" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentBase", propOrder = {
    "qos",
    "filterSource",
    "filterTarget"
})
@XmlSeeAlso({
    VoltageAgent.class,
    SensorAgent.class,
    JSONAgent.class,
    TcpAgent.class,
    MWDAgent.class,
    SerialAgent.class,
    TrackAgent.class,
    ConsoleAgent.class,
    MeteoAgent.class,
    SimulatorAgent.class,
    GPXPlayerAgent.class,
    GPSStatusAgent.class,
    AISAgent.class,
    GyroAgent.class,
    UdpAgent.class
})
public class AgentBase {

    protected String qos;
    @XmlElement(name = "FilterSource")
    protected FilterSource filterSource;
    @XmlElement(name = "FilterTarget")
    protected FilterTarget filterTarget;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "active")
    protected Boolean active;

    /**
     * Gets the value of the qos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQos() {
        return qos;
    }

    /**
     * Sets the value of the qos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQos(String value) {
        this.qos = value;
    }

    /**
     * Gets the value of the filterSource property.
     * 
     * @return
     *     possible object is
     *     {@link FilterSource }
     *     
     */
    public FilterSource getFilterSource() {
        return filterSource;
    }

    /**
     * Sets the value of the filterSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterSource }
     *     
     */
    public void setFilterSource(FilterSource value) {
        this.filterSource = value;
    }

    /**
     * Gets the value of the filterTarget property.
     * 
     * @return
     *     possible object is
     *     {@link FilterTarget }
     *     
     */
    public FilterTarget getFilterTarget() {
        return filterTarget;
    }

    /**
     * Sets the value of the filterTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterTarget }
     *     
     */
    public void setFilterTarget(FilterTarget value) {
        this.filterTarget = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isActive() {
        if (active == null) {
            return false;
        } else {
            return active;
        }
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

}
