//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.11 at 08:21:36 AM CEST 
//


package com.aboni.nmea.router.conf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Filter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" default="*" />
 *       &lt;attribute name="sentence" type="{http://www.w3.org/2001/XMLSchema}string" default="*" />
 *       &lt;attribute name="talker" type="{http://www.w3.org/2001/XMLSchema}string" default="*" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filter")
public class Filter {

    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "sentence")
    protected String sentence;
    @XmlAttribute(name = "talker")
    protected String talker;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        if (source == null) {
            return "*";
        } else {
            return source;
        }
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the sentence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentence() {
        if (sentence == null) {
            return "*";
        } else {
            return sentence;
        }
    }

    /**
     * Sets the value of the sentence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentence(String value) {
        this.sentence = value;
    }

    /**
     * Gets the value of the talker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTalker() {
        if (talker == null) {
            return "*";
        } else {
            return talker;
        }
    }

    /**
     * Sets the value of the talker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTalker(String value) {
        this.talker = value;
    }

}
