//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.11 at 08:21:36 AM CEST 
//


package com.aboni.nmea.router.conf;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;


/**
 * <p>Java class for Router complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Router">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Log" type="{}Log"/>
 *         &lt;element name="GPSPriority" type="{}List"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="SerialAgent" type="{}SerialAgent"/>
 *           &lt;element name="TcpAgent" type="{}TcpAgent"/>
 *           &lt;element name="UdpAgent" type="{}UdpAgent"/>
 *           &lt;element name="ConsoleAgent" type="{}ConsoleAgent"/>
 *           &lt;element name="TrackAgent" type="{}TrackAgent"/>
 *           &lt;element name="SensorAgent" type="{}SensorAgent"/>
 *           &lt;element name="VoltageAgent" type="{}VoltageAgent"/>
 *           &lt;element name="GyroAgent" type="{}GyroAgent"/>
 *           &lt;element name="SimulatorAgent" type="{}SimulatorAgent"/>
 *           &lt;element name="MeteoAgent" type="{}MeteoAgent"/>
 *           &lt;element name="MWDAgent" type="{}MWDAgent"/>
 *           &lt;element name="GPXPlayerAgent" type="{}GPXPlayerAgent"/>
 *           &lt;element name="JSONAgent" type="{}JSONAgent"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Router", propOrder = {
    "log",
    "gpsPriority",
    "serialAgentOrTcpAgentOrUdpAgent"
})
public class Router {

    @XmlElement(name = "Log", required = true)
    protected Log log;
    @XmlElement(name = "GPSPriority", required = true)
    protected com.aboni.nmea.router.conf.List gpsPriority;
    @XmlElements({
            @XmlElement(name = "SerialAgent", type = SerialAgent.class),
            @XmlElement(name = "TcpAgent", type = TcpAgent.class),
            @XmlElement(name = "UdpAgent", type = UdpAgent.class),
            @XmlElement(name = "ConsoleAgent", type = ConsoleAgent.class),
            @XmlElement(name = "TrackAgent", type = TrackAgent.class),
            @XmlElement(name = "SensorAgent", type = SensorAgent.class),
            @XmlElement(name = "VoltageAgent", type = VoltageAgent.class),
            @XmlElement(name = "GyroAgent", type = GyroAgent.class),
            @XmlElement(name = "SimulatorAgent", type = SimulatorAgent.class),
            @XmlElement(name = "MeteoAgent", type = MeteoAgent.class),
            @XmlElement(name = "MWDAgent", type = MWDAgent.class),
            @XmlElement(name = "GPXPlayerAgent", type = GPXPlayerAgent.class),
            @XmlElement(name = "JSONAgent", type = JSONAgent.class)
    })
    protected java.util.List<AgentBase> serialAgentOrTcpAgentOrUdpAgent;

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the gpsPriority property.
     * 
     * @return
     *     possible object is
     *     {@link com.aboni.nmea.router.conf.List }
     *     
     */
    public com.aboni.nmea.router.conf.List getGPSPriority() {
        return gpsPriority;
    }

    /**
     * Sets the value of the gpsPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.aboni.nmea.router.conf.List }
     *     
     */
    public void setGPSPriority(com.aboni.nmea.router.conf.List value) {
        this.gpsPriority = value;
    }

    /**
     * Gets the value of the serialAgentOrTcpAgentOrUdpAgent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serialAgentOrTcpAgentOrUdpAgent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSerialAgentOrTcpAgentOrUdpAgent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SerialAgent }
     * {@link TcpAgent }
     * {@link UdpAgent }
     * {@link ConsoleAgent }
     * {@link TrackAgent }
     * {@link SensorAgent }
     * {@link VoltageAgent }
     * {@link GyroAgent }
     * {@link SimulatorAgent }
     * {@link MeteoAgent }
     * {@link MWDAgent }
     * {@link GPXPlayerAgent }
     * {@link JSONAgent }
     *
     *
     */
    public java.util.List<AgentBase> getSerialAgentOrTcpAgentOrUdpAgent() {
        if (serialAgentOrTcpAgentOrUdpAgent == null) {
            serialAgentOrTcpAgentOrUdpAgent = new ArrayList<AgentBase>();
        }
        return this.serialAgentOrTcpAgentOrUdpAgent;
    }

}
