//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 08:25:51 AM CEST 
//


package com.aboni.nmea.router.conf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrackAgent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackAgent">
 *   &lt;complexContent>
 *     &lt;extension base="{}AgentBase">
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Track" />
 *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="sentence" type="{http://www.w3.org/2001/XMLSchema}string" default="RMC" />
 *       &lt;attribute name="interval" type="{http://www.w3.org/2001/XMLSchema}int" default="30" />
 *       &lt;attribute name="intervalStatic" type="{http://www.w3.org/2001/XMLSchema}int" default="1800" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackAgent")
public class TrackAgent
    extends AgentBase
{

    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "file")
    protected String file;
    @XmlAttribute(name = "sentence")
    protected String sentence;
    @XmlAttribute(name = "interval")
    protected Integer interval;
    @XmlAttribute(name = "intervalStatic")
    protected Integer intervalStatic;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Track";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        if (file == null) {
            return "";
        } else {
            return file;
        }
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the sentence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentence() {
        if (sentence == null) {
            return "RMC";
        } else {
            return sentence;
        }
    }

    /**
     * Sets the value of the sentence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentence(String value) {
        this.sentence = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getInterval() {
        if (interval == null) {
            return  30;
        } else {
            return interval;
        }
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInterval(Integer value) {
        this.interval = value;
    }

    /**
     * Gets the value of the intervalStatic property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getIntervalStatic() {
        if (intervalStatic == null) {
            return  1800;
        } else {
            return intervalStatic;
        }
    }

    /**
     * Sets the value of the intervalStatic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntervalStatic(Integer value) {
        this.intervalStatic = value;
    }

}
