//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.25 at 10:40:01 AM CET 
//


package com.aboni.nmea.router.conf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aboni.nmea.router.conf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Router_QNAME = new QName("", "Router");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aboni.nmea.router.conf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Router }
     * 
     */
    public Router createRouter() {
        return new Router();
    }

    /**
     * Create an instance of {@link SimulatorAgent }
     * 
     */
    public SimulatorAgent createSimulatorAgent() {
        return new SimulatorAgent();
    }

    /**
     * Create an instance of {@link FilterSet }
     * 
     */
    public FilterSet createFilterSet() {
        return new FilterSet();
    }

    /**
     * Create an instance of {@link SensorAgent }
     * 
     */
    public SensorAgent createSensorAgent() {
        return new SensorAgent();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link TcpAgent }
     * 
     */
    public TcpAgent createTcpAgent() {
        return new TcpAgent();
    }

    /**
     * Create an instance of {@link MWDAgent }
     * 
     */
    public MWDAgent createMWDAgent() {
        return new MWDAgent();
    }

    /**
     * Create an instance of {@link SerialAgent }
     * 
     */
    public SerialAgent createSerialAgent() {
        return new SerialAgent();
    }

    /**
     * Create an instance of {@link UdpAgent }
     * 
     */
    public UdpAgent createUdpAgent() {
        return new UdpAgent();
    }

    /**
     * Create an instance of {@link TrackAgent }
     * 
     */
    public TrackAgent createTrackAgent() {
        return new TrackAgent();
    }

    /**
     * Create an instance of {@link AgentBase }
     * 
     */
    public AgentBase createAgentBase() {
        return new AgentBase();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ConsoleAgent }
     * 
     */
    public ConsoleAgent createConsoleAgent() {
        return new ConsoleAgent();
    }

    /**
     * Create an instance of {@link MeteoAgent }
     * 
     */
    public MeteoAgent createMeteoAgent() {
        return new MeteoAgent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Router }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Router")
    public JAXBElement<Router> createRouter(Router value) {
        return new JAXBElement<Router>(_Router_QNAME, Router.class, null, value);
    }

}
